### ISSUE TITLE
Zabbix 5.2+ uses other name for zabbix-release package

### ISSUE THREAD

**Issue by syphernl** [Revenni/zabbix_agent2#1]
In Zabbix < 5.2 the zabbix-release package was named `zabbix-release_5.0-1+focal_all.deb` (with the `ansible_distribution_release`) however with Zabbix >= 5.2 it is now changed to `zabbix-release_5.2-1+ubuntu20.04_all.deb` which should use the `ansible_distribution_version` instead.

**Comment by VinceHillier** [comment]
Thanks Frank.  

Updated!

**Comment by syphernl** [comment]
Wow that was fast, thanks Vince!
